### ISSUE TITLE
Question about GPT4 generated answer

### ISSUE THREAD

**Issue by KimperYang** [TemporaryLoRA/Block-Attention#3]
Thanks for your great work! It seems there is no scripts of generating GPT answer for the training data, thus making it hard to reproduce the training set you used for the experiments. Could you please add it, or provide the prompt for generating the answers.

In addition, would you release the checkpoints of your finetuned model by any chance? Thank you.

**Comment by libertywing** [comment]
No problem we will upload the dataset soon (this weekend).




As for checkpoints, its hard for us to release them since they are stored in our company's servers.




Best,

Yan




----- Original Message -----
From: "Jingbo Yang" ***@***.***>
To: TemporaryLoRA/Block-Attention ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Thu, 19 Dec 2024 16:04:33 -0800
Subject: [TemporaryLoRA/Block-Attention] Question about GPT4 generated answer (Issue #3)



Thanks for your great work! It seems there is no scripts of generating GPT answer for the training data, thus making it hard to reproduce the training set you used for the experiments. Could you please add it, or provide the prompt for generating the answers.

In addition, would you release the checkpoints of your finetuned model by any chance? Thank you.

**Comment by KimperYang** [comment]
Thanks!
